export const events = [
    "Great Goose Wars",
    "Migration",
    "Goose Attack",
    "Nesting Season",
    "Goose Fight",
    "Molting Season",
    "Goose Battle Season",
    "Egg Laying Season",
    "Time of the Goose",
    "Year of the Goose",
    "Final Exams",
    "Midterms",
    "8:30 Classes",
    "Winter",
    "Summer",
];
