export const events = [
    "Great Goose Wars",
    "Migration",
    "Goose Attack",
    "Nesting Season",
    "Goose Fight",
    "Molting Season",
    "Goose Battle Season",
    "Egg Laying Season",
    "Time of the Goose",
    "Year of the Goose",
    "Final Exams",
    "Midterms",
    "8:30 am Classes",
    "Winter",
    "Summer",
    "Summer Holidays",
    "Reading Week",
    "Goose Season",
    "The Great Goosening",
    "Time for the Goose",
    "Birth of the Goose",
    "Hatching Season",
    "The Great Hatching",
    "The Hatching of Mr. Goose",
    "Meeting of the Geese",
];
