export const people = [
    "Mr. Goose",
    "The Evil Goose",
    "Greg the Goose",
    "Ryan Gooseling",
    "Little Goose",
    "mr goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mrs. Goose",
    "Ms. Goose",
    "Goose Goose",
    "Duck",
    "Goose Directory",
];
