export const people = [
    "Mr. Goose",
    "The Evil Goose",
    "Greg the Goose",
    "Ryan Gooseling",
    "Little Goose",
    "mr goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mr. Goose",
    "Mrs. Goose",
    "Ms. Goose",
    "Goose Goose",
    "Duck",
    "Goose Directory",
    "The Goosinator",
    "Big Goose",
    "Goose Johnson",
    "Justin Goose",
    "Donald Goose",
    "Mr. Honk",
    "Tom Honks",
    "Daffy Goose",
    "Goose President",
    "Goose Dictator",
    "King of Geese",
];
