export const places = [
    "Nest",
    "Campus",
    "uWaterloo",
    "MC",
    "Goose Town",
    "MC Square",
    "Goose Gathering",
    "Tim Horton's",
    "Goose Group",
    "Goose City",
    "Goose Village",
    "Nesting Area",
    "Goose Square",
    "DC",
    "Bubble Tea",
    "The Pond",
    "The Lake",
    "The Puddle",
    "The Middle of The Road",
    "The Fields",
    "Tim Horton's",
    "Great Nest",
    "Goose House",
    "Goose Station",
];
