const caselessReplacements = [
    ["people", "geese"],
    ["men", "gander"],
    ["males", "gander"],
    ["man", "gander"],
    ["male", "gander"],
    ["women", "geese"],
    ["females", "geese"],
    ["woman", "goose"],
    ["female", "goose"],
    ["science", "goose math"],
    ["technology", "goose surveillance"],
    ["art", "goose drawing"],
    ["philosophy", "goose thinking"],
    ["finance", "goose counting"],
    ["culture", "goose collecting"],
    ["education", "goose raising"],
    ["game", "goosey activity"],
    ["bad", "anti-goose"],
    ["good", "goosey"],
    ["wrong", "ungooseable"],
    ["law", "goose rule"],
    ["laws", "goose rules"],
    ["fact", "goose fact"],
    ["facts", "goose facts"],
    ["job", "goose profession"],
    ["jobs", "goose professions"],
    ["professional", "official goose"],
    ["professionals", "official geese"],
    ["senator", "proud goose"],
    ["senators", "proud geese"],
    ["big", "goose-sized"],
    ["small", "egg-sized"],
    ["animal", "goose-being"],
    ["endangered", "less cool than a goose"],
    ["extinct", "about as cool as a goose"],
    ["slave", "servant goose"],
    ["slavery", "goose ownership"],
    ["slaves", "servant geese"],
    ["capita", "goose"],
    ["holiday", "goose-break"],
    ["holidays", "goose-breaks"],
    ["competition", "goose-off"],
    ["competitions", "goose-offs"],
    ["cold", "colder than a goose with no feathers"],
    ["warm", "warmer than a double-feathered goose"],
    ["hot", "warmer than a double-feathered goose"],
    ["water", "goose liquid"],
    ["sunlight", "Mr. Goose's Light"],
    ["band", "goose group"],
    ["genus", "Goose-Type"],
    ["kingdom", "Goose-Category"],
    ["class", "Goose-Class"],
    ["father", "adoptive goose dad"],
    ["mother", "adoptive goose mom"],
    ["parents", "adoptive goose family"],
    ["references", "Straight from the goose's mouth"],
    ["wikipedia", "Goosepedia"],
    ["see also", "Geese also liked"],
    ["website", "Goose Paper"],
    ["country", "Goose Alliance"],
    ["county", "Goose Subdivision"],
    ["external links", "Other Geese"],
    ["village", "goose-gathering"],
    ["town", "goose-group"],
    ["hamlet", "group of geese"],
    ["south", "tailwards"],
    ["north", "beakwards"],
    ["kilometre", "wing-flap"],
    ["kilometres", "wing-flaps"],
    ["km", "wing-flaps"],
    ["mile", "big-honk"],
    ["miles", "big-honks"],
    ["mi", "big-honks"],
    ["population", "goose count"],
    ["capital", "head of goose government"],
    ["historic", "goose-worn"],
    ["said", "honked"],
    ["says", "honks"],
    ["say", "honk"],
    ["claimed", "honked"],
    ["claims", "honks"],
    ["claim", "honk"],
    ["played", "pretended to be a goose"],
    ["play", "pretend to be a goose"],
    ["plays", "pretends to be a goose"],
    ["group", "flock"],
    ["qualified", "defeated geese"],
    ["struggles", "honks"],
    ["daily", "biweekly"],
    ["child", "gosling"],
    ["children", "goslings"],
    ["sibling", "goose friend"],
    ["siblings", "goose friends"],
    ["farm", "goose farm"],
    ["career", "goose"],
    ["well known", "liked by the geese"],
    ["hospital", "goose hospital"],
    ["hospitals", "goose hospitals"],
    ["school", "goose school"],
    ["schools", "goose schools"],
    ["university", "goose school"],
    ["university", "goose schools"],
    ["chemical", "goose substance"],
    ["chemicals", "goose substances"],
    ["antibiotic", "goose substance"],
    ["antibiotics", "goose substances"],
    ["doctor", "goose medic"],
    ["doctors", "goose medics"],
    ["human", "goose"],
    ["humans", "geese"],
    ["media", "goose news"],
    ["story", "goose tale"],
    ["teacher", "wise goose"],
    ["professor", "wise goose"],
    ["underpaid", "eggless"],
    ["humanity", "goose-kind"],
    ["mankind", "goose-kind"],
    ["team", "flock"],
    ["teams", "flocks"],
    ["territory", "goose pond"],
    ["unknown", "unknown to all geese"],
    ["family", "goose family"],
    ["families", "goose families"],
    ["district", "goose area"],
    ["medal", "goose"],
    ["olympics", "Goose Battle"],
    ["politics", "goose fight"],
    ["politician", "loud goose"],
    ["politicians", "loud geese"],
    ["film", "goose story"],
    ["films", "goose stories"],
    ["book", "goose propaganda pamphlet"],
    ["books", "goose propaganda pamphlets"],
    ["legal", "goose-related"],
    ["court", "group of goose judges"],
];

export const replacements = [
    ...caselessReplacements,
    ...(caselessReplacements.map(([from, to]) => [`${from.slice(0, 1).toUpperCase()}${from.slice(1)}`, `${to.slice(0, 1).toUpperCase()}${to.slice(1)}`])),
];
